languageCode:           "en"
title:                  "Murk"
baseURL:                "https://murk.wangkanai.com"
enableInlineShortcodes: true

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

module:
   mounts:
      - source:           dist
        target:           static/dist
      - source:           site/assets
        target:           assets
      - source:           site/content
        target:           content
      - source:           site/data
        target:           data
      - source:           site/layouts
        target:           layouts
      - source:           site/static
        target:           static
      - source:           site/static/favicons
        target:           static


params:
   description:         "Admin portal dark and mobile first frontend framework"
   authors:             "Sarin Na Wangkanai"
   current_version:      "0.0-dev1"
   docs_version:         "1.0"
