name: Pages
on:
   push:
      branches:
         - main
env:
   CI: true
   NODE: 14.x

jobs:
   pages:
      runs-on: ubuntu-latest

      steps:
         -  name: Clone repository
            uses: actions/checkout@v2

         -  name: Set Node.js version
            uses: actions/setup-node@v1
            with:
               node-version: "${{ env.NODE }}"

         -  name: Set up npm cache
            uses: actions/cache@v2
            with:
               path: ~/.npm
               key: ${{ runner.os }}-node-v${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
               restore-keys: |
                  ${{ runner.OS }}-node-v${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
                  ${{ runner.OS }}-node-v${{ env.NODE }}-

         -  name: Install npm dependencies
            run: npm ci

         -  name: Build CSS
            run: npm run css

         -  name: Build docs
            run: npm run docs

         -  name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
               github_token: ${{ secrets.GITHUB_TOKEN }}
               publish_dir: ./public
